/* Generated By:JJTree: Do not edit this line. ASTdiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdiv extends SimpleNode {
  public ASTdiv(int id) {
    super(id);
  }

  public ASTdiv(Prog03 p, int id) {
    super(p, id);
  }
  public ASTdiv clone(int id){
	return new ASTdiv(id);
   }
}
/* JavaCC - OriginalChecksum=ca190e45d1b10f343fb7eaf44b8a8925 (do not edit this line) */
