/* Generated By:JJTree: Do not edit this line. ASTmul.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmul extends SimpleNode {
  public ASTmul(int id) {
    super(id);
  }

  public ASTmul(Prog03 p, int id) {
    super(p, id);
  }
    public ASTmul clone(int id){
	return new ASTmul(id);
    }
}
/* JavaCC - OriginalChecksum=8d659dfc6108ef82871dbc6a0a7f8fa4 (do not edit this line) */
